### ISSUE TITLE
Wrong information about Interface

### ISSUE THREAD

**Issue by ghost** [manojpramesh/solidity-cheatsheet#12]
- https://github.com/manojpramesh/solidity-cheatsheet#interface

### Interfaces can inherit from other interfaces.

**Example**

```solidity

interface IERC20 { ... }

interface WETH is IERC20  { ... }

```

---

### Solidity 0.6.x features

- https://blog.soliditylang.org/2020/06/18/solidity-0.6-inheritance/

**Comment by manojpramesh** [comment]
This document still follows 0.5.x. Currently working on updating and versioning each release. Will push soon.
